PolymerElements/paper-dropdown-menu

- paper-dropdown-menu.html
This prevents the focusable element from getting buried in extra layers
of DOM, making it difficult to decide what should or should not be
focused.
Related to https://github.com/PolymerElements/paper-menu-button/pull/19
Related to https://github.com/PolymerElements/iron-dropdown/pull/22
Combined, these PRs close https://github.com/PolymerElements/paper-dropdown-menu/issues/9
> Don't wrap dropdown content.

- paper-dropdown-menu.html
- test/paper-dropdown-menu.html
This is enabled by listening for a bubbling `iron-deselect` event and
setting the current selection to `null` when it is received.
Fixes #39
> Dropdown values can be deselected.

- paper-dropdown-menu.html
Fixes https://github.com/PolymerElements/paper-dropdown-menu/issues/31
Before:
After:
> fix dropdown on ie

- paper-dropdown-menu.html
Fixes https://github.com/PolymerElements/paper-dropdown-menu/issues/7#issuecomment-145831835. The contained `paper-menu-button` was getting a `padding: 8px`, so this PR mostly undoes it from everywhere.
This is the straight-up the element demo, with a plain `paper-input` of a fixed width. The only change is that I removed the `text-align: center` on the `horizontal-section` to make sure the text lines up too.
Before:
And the ripple, just to make sure I didn't break that:
After:
And the ripple:
> fix dropdown padding

- bower.json
- paper-dropdown-menu.html
- test/paper-dropdown-menu.html
Fixes https://github.com/PolymerElements/paper-dropdown-menu/issues/32, https://github.com/PolymerElements/paper-dropdown-menu/issues/54
- adds the `IronFormElementBehaviour` so that it can be tracked in an `iron-form`
- adds the `IronValidatableBehaviour` so that no-selection, required dropdowns are invalid
- continues to not be able to spell `behaviour` the american way outside of code
> add form behaviour

- demo/index.html
- paper-dropdown-menu.html
R: @cdata @notwaldorf 
We need this for code-labs.io. Our use case it that the dropdown is at the bottom of the page and opening the menu downwards doesn't make sense.
> Fixes #6 - add vertical/horizontalAlign properties forwarded to paper-menu-button

- paper-dropdown-menu.html
Dropdown is not intended to act as a selectable, and in fact, this is never used in the list of behaviors.
> Remove unnecessary import.

- paper-dropdown-menu.html
Demo uses paper-listbox. However the Example still uses paper-menu.  I understand that Readme is generated automatically. Please let me know if I need to fix it manually.
> Update example to use paper-listbox to be consistent with demo

- paper-dropdown-menu.html
This was spurred by a conversation on polymer-dev. I think this is a little clearer, because we expect people to provide a child element that fires `iron-select`, but listening for that `iron-select` is probably one of the key ways to get the output of the element. 
Although you can also bind to `value`, `selectedItem`, or `selectedItemLabel`, which I didn't mention. Hm... Well, anyway, it's a start.
Perhaps the example should show one of these things (for example, binding to `value` or `selectedItemLabel`) as well to make it more of a complete example?
> Fix #127. Clarify API doc about menu child, events.

- bower.json
- demo/index.html
- paper-dropdown-menu-light.html
- paper-dropdown-menu-shared-styles.html
- test/index.html
- test/paper-dropdown-menu-light.html
Put `paper-dropdown` on the treadmill:
- replace `paper-input` with a styled div. I had originally made this styled div a separate element (because it's got a bunch of styles), but since we had to bind down all the value/label/focused/disabled etc related properties this was actually a bit expensive. 
- add a lazy ripple for bonus points (because there's no reason we don't do this already; I'll add this to plain `paper-dropdown-menu` in a different PR
Code details to make review easier:
- most of the code is actually from `paper-dropdown-menu`. The only thing that is new is the `<div class="container` and its styles, `hasContent`, and the 2 private methods at the end
- all the tests are `100%` copied from `paper-dropdown-menu`
- I moved the styles to a separate file so they can be shared …
> accio paper-dropdown-light! ⚡️

- paper-dropdown-menu-light.html
`paper-dropdown-menu`'s value is always a string, so this isn't needed
> remove unused/vestigial paper-input code

- bower.json
- paper-dropdown-menu.html
Adding an allow-scroll-lock property implemented in `iron-dropdown` [PR #25](https://github.com/PolymerElements/iron-dropdown/pull/25), to make it accessible in `paper-dropdown-menu`. This depends on 'paper-menu-button' [PR #35](https://github.com/PolymerElements/paper-menu-button/pull/35) being merged.
> Add allow-outside-scroll property

- paper-dropdown-menu-light.html
```allow-outside-scroll``` property in response to @valdrinkoshi's https://github.com/PolymerElements/paper-dropdown-menu/pull/70#issuecomment-231261450
> Add allow-outside-scroll to light theme

- paper-dropdown-menu-light.html
- paper-dropdown-menu.html
Fixes #153 by changing the `role="button"` to be a `span` rather than a `div`, so that a `:before` pseudo element can be rendered on the left of the internal `paper-menu-button` http://jsbin.com/fegoho/4/edit?html,output
> div to span

- bower.json
- paper-dropdown-menu-light.html
- paper-dropdown-menu.html
Adding the `close-on-activate` attribute will close the menu when it receives any `iron-activate` event.
Fixes #163, #72
> Fixes #163: Adds `close-on-activate` attribute.

- paper-dropdown-menu-light.html
- test/paper-dropdown-menu-light.html
This is copy-pasted from @miztroh's contribution in #131 + `s/paper-dropdown-menu/\0-light/g`.
> Follow up to #131, which was created before paper-dropdown-menu-light.

- paper-dropdown-menu-light.html
Fixes https://github.com/PolymerElements/paper-dropdown-menu/issues/143
Also fixed how we centered the text and the icon: originally I used a `min-height` on the text, of the same height as the icon, but that's silly if you ever change the font size. Fixed that with some math.
> fix paper-dropdown-light styles

- paper-dropdown-menu-light.html
Fixes https://github.com/PolymerElements/paper-dropdown-menu/issues/181
- the original `<label>` used `visibility`, not `display:none` when floating the label. This makes sense for this case too, since `display:none`-ing the label will also remove the `:after`, which is the underline
- removed the animation duration if the label doesn't need to float, as this lead to a brief 0.2s of text overlap between the label and the selected text
PTAL @bicknellr, cc @mgiuffrida
> fix focus underline when there's no label

- paper-dropdown-menu-shared-styles.html
The mouse cursor pointer settings are nicer to have on the paper-menu-button instead of the paper-dropdown-menu. Setting the cursor here cascades into the scroll bar of the dropdown content. It's nicer to set the cursor to pointer in just the trigger within the paper-menu-button.
> Remove the cursor pointer setting

- paper-dropdown-menu-light.html
Removing cursor: pointer that is now redundant with the change in 
https://github.com/PolymerElements/paper-dropdown-menu/pull/198
> Removing a line that is now redundant

- paper-dropdown-menu-light.html
Currently the icon is not displayed.
Also, sorted the imports.
> Add missed iron-icon import

- paper-dropdown-menu.html
Paper-dropdown-menu creates a child paper-menu-button.  Paper-menu-button has a restore-focus-on-close property, but there is currently no way for components with a paper-dropdown-menu to set this property.  This will allow components with a paper-dropdown-menu to choose not to have focus set on the menu when the menu closes.
> Allow restoreFocusOnClose to be set on paper-dropdown-menu

- bower.json
This pull requests want to make this Polymer element consistent with the majority of other Polymer elements. The uppercase version "PolymerElements" is closer to real name of the github project name, like presented in the git URL.
The use of mixed case does not seem to have an effect on bower and JavaScript projects. But other languages like Java are more picky and would benefit from consistency.
@valdrinkoshi asked me if I can make a pull request for the 1.x branch now in the request for 2.0-preview branch #243 
This pull request is a manual follow up of PolymerLabs/tedium#47 and PolymerLabs/tedium#48 which try to do this in an automated way, but are stuck.
> from polymerelements to PolymerElements in 1.x

- demo/index.html
- paper-dropdown-menu-light.html
- paper-dropdown-menu.html
This lets the user position the dropdown content below the trigger. If a
vertical offset is not provided, it gets computed as it was previously.
> Add option to pass custom value to vertical offset

- demo/index.html
- paper-dropdown-menu-light.html
- paper-dropdown-menu.html
This lets the user position the dropdown content below the trigger. If a
vertical offset is not provided, it gets computed as it was previously.
> Add option to pass custom value to vertical offset (to 1.x)

- paper-dropdown-menu-light.html
- paper-dropdown-menu.d.ts
- paper-dropdown-menu.html
Makes things easier on closure compiler.
This externalizes a CL from @MatrixFrog. See [go/polymer-upstream](http://goto.google.com/polymer-upstream)
> Remove noop IIFE

- .travis.yml
- demo/index.html
- package-lock.json
- package.json
- paper-dropdown-menu-light.d.ts
- paper-dropdown-menu-light.html
- paper-dropdown-menu.html
- test/index.html
- test/paper-dropdown-menu-light.html
- test/paper-dropdown-menu.html
Runs the experimental autoformatter [webmat](https://github.com/PolymerLabs/webmat) which runs clang-format on js files and makes it so that it can run on HTML files. Please look through this PR with `?w=1` in the diff to make sure that no logic was changed.
What has changed?
You can run the formatter on the whole project by running `npm run format` and ex/include files from the formatter, and enter your custom clang-format config in a formatconfig.json see webmat readme for more!
> Automatic format!

- package-lock.json
- package.json
- paper-dropdown-menu-light.js
- paper-dropdown-menu-shared-styles.js
- paper-dropdown-menu.js
This PR overrides `_attachDom` so that `delegatesFocus` can be set when attaching the shadow root. This is going into #317 instead of master.
> Delegate focus to the internal button
