- paper-dropdown-menu.html
> IronButtonState depends on IronControlState.

- demo/index.html
- paper-dropdown-menu.html
- test/paper-dropdown-menu.html
Depends on https://github.com/PolymerElements/paper-menu-button/pull/15
Closes https://github.com/PolymerElements/paper-dropdown-menu/issues/3
> Properly display preselected values from content.

- README.md
Tiny tweak to improve readability
> Add syntax highlighting to the readme

- paper-dropdown-menu.html
Boolean is the weird Object typed thing you get with new Boolean('lol')
> Boolean -> boolean

- .travis.yml
- bower.json
- demo/index.html
- paper-dropdown-menu.html
- test/paper-dropdown-menu.html
- Div with role=button needs to exist for reasons
- Make the input type=text for the same reasons
- Sync aria-expanded with opened state
Fixes #30
> Use combobox role with paper-listbox

- demo/index.html
- paper-dropdown-menu.html
Reverts PolymerElements/paper-dropdown-menu#91
> Revert "Fixes #6 - add vertical/horizontalAlign properties forwarded to paper-menu-button"

- demo/index.html
- paper-dropdown-menu.html
> Fixes #6. Second attempt

- paper-dropdown-menu.html
> Fixup _getValidity for the compiler

- paper-dropdown-menu.html
- test/paper-dropdown-menu.html
Fixes #26 by removing non-existing events.
> cleanup non-existing events

- bower.json
- demo/index.html
- paper-dropdown-menu-icons.html
- paper-dropdown-menu.html
> Add custom icon set for perf. Fixes #38

- paper-dropdown-menu-light.html
Adds tabindex to hostAttributes, removes outline from focus style (focus is shown with underline color / size).
> Fixes #165: Adds tabindex, fixes focus styles.

- paper-dropdown-menu-light.html
Fixes #179 by setting cursor: pointer on the label.
> paper-dropdown-menu-light cursor

- paper-dropdown-menu.html
Add `dynamic-align` property by proxying it to `<paper-menu-button>`.
> Add dynamic-align property

- .gitignore
- .travis.yml
- README.md
- bower.json
- demo/index.html
- paper-dropdown-menu-light.html
- paper-dropdown-menu-shared-styles.html
- paper-dropdown-menu.html
- test/index.html
- test/paper-dropdown-menu-light.html
- test/paper-dropdown-menu.html
> port to 2.0

- paper-dropdown-menu-light.html
Use compound selector on elements for RTL styling.
Can be merged as https://github.com/Polymer/polymer/pull/4970 is released in polymer v2.3.0
> use :dir as compound selector

- README.md
> import web animations for wc.org demo

- paper-dropdown-menu-light.html
- paper-dropdown-menu.html
> value settable so it can be reset by forms

- demo/index.html
Fixes alignment of menus in the demo page
> Align menus horizontally

- demo/index.html
- paper-dropdown-menu-light.js
- paper-dropdown-menu-shared-styles.js
fixes issue where we set text-align to always left
> RTL support for 3.x

- package-lock.json
- package.json
- paper-dropdown-menu-light.js
- paper-dropdown-menu.js
---
paper-dropdown-menu-light is not a combobox: a combobox contains a
user-editable text area for arbitrary inputs with a popup for suggestions
(usually a 'listbox') and this element does not allow arbitrary user input.
paper-dropdown-menu-light is a 'collapsible dropdown listbox'. See this link
for an example of this behavior:
https://www.w3.org/TR/wai-aria-practices-1.1/examples/listbox/listbox-collapsible.html.
Given these issues with the current state of the element, I've made these
changes:
- Update role from "combobox" to "button".
This element isn't a combobox: it is a button that opens a popup of some
kind, typically containing a listbox.
- Remove the `aria-autocomplete` attribute.
There is nothing to autocomplete because this element does not contain a
user-editable text input. …
> Fix accessibility descriptions. (...)

- paper-dropdown-menu-light.js
- test/paper-dropdown-menu-light.html
- test/paper-dropdown-menu.html
> Upstream cl/326093618: Fix incorrect height on deselection.
